name: CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    name: ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - cabal: "3.0.0.0"
            ghc: "8.8.4"

    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/master'

    - uses: actions/setup-haskell@v1
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - uses: actions/cache@v1
      name: Cache ~/.cabal/store
      with:
        path: ~/.cabal/store
        key: ${{ runner.os }}-${{ matrix.ghc }}-cabal

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends ninja-build libopenblas-dev libhdf5-dev

    - name: Build
      run: |
        cabal v2-update
        cabal v2-build --dependencies-only

        # - name: Test
        #   run: |
        #     cabal v2-test --enable-tests --test-show-details=direct

    - name: Create AppImage
      if: ${{ matrix.ghc }} == "8.8.4"
      run: |
        echo Hello world!
